blank_issues_enabled: false
contact_links:
  - name: Contributing
    url: https://github.com/signified/.github/blob/main/CONTRIBUTING.md
    about: Guidelines for contributing to Signified projects.
  - name: Code of Conduct
    url: https://github.com/signified/.github/blob/main/CODE_OF_CONDUCT.md
    about: Code of conduct for contributing to Signified projects.
  - name: Security
    url: https://github.com/signified/.github/blob/main/SECURITY.md
    about: Report a security vulnerability.
  - name: Contact
    url: https://signified.com.au/contact
    about: Contact Signified.
